### ISSUE TITLE
[Errno 22] Invalid argument on Windows 10

### ISSUE THREAD

**Issue by camlloyd** [ome/conda-bftools#2]
conda create -n bftools -c ome bftools
Running this as described in #1 works as expected using a clean install of Miniconda3 on macOS/spun-up Ubuntu 20.04 VM, but produces the error below on Windows 10. 

<details>
  <summary>Expand</summary>

(base) C:\>conda create -n bftools -c ome bftools
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\ProgramData\Miniconda3\envs\bftools

  added / updated specs:
    - bftools

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    bftools-6.3.1              |                1        33.7 MB  ome
    openjdk-11.0.6             |       he774522_1       295.7 MB
    ------------------------------------------------------------
                                           Total:       329.3 MB

The following NEW packages will be INSTALLED:

  bftools            ome/noarch::bftools-6.3.1-1
  openjdk            pkgs/main/win-64::openjdk-11.0.6-he774522_1

Proceed ([y]/n)? y

Downloading and Extracting Packages
bftools-6.3.1        | 33.7 MB   | ############################################################################ | 100%
openjdk-11.0.6       | 295.7 MB  | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
ERROR conda.core.link:_execute(700): An error occurred while installing package 'ome::bftools-6.3.1-1'.
Rolling back transaction: done

[Errno 22] Invalid argument: 'C:\\ProgramData\\Miniconda3\\pkgs\\bftools-6.3.1-1\\bin\\bf.sh'
()

(base) C:\>

</details>

**Comment by joshmoore** [comment]
Thanks, @camlloyd. I've pushed a `bld.bat` file if you would like to test:

```
conda install conda-build
conda build .
```

Just working on the deployment to anaconda.org now.

**Comment by camlloyd** [comment]
This issue also affects the recipes for:

- [ ] [ome/conda-bioformats2raw](https://github.com/ome/conda-bioformats2raw)
- [ ] [ome/conda-raw2ometiff](https://github.com/ome/conda-raw2ometiff)

right?

**Comment by joshmoore** [comment]
Definitely. Still working on getting the Azure builds to upload the artifacts, and then I'll roll out to the rest.

see: https://dev.azure.com/openmicroscopy/conda-bftools/_build?definitionId=2

**Comment by joshmoore** [comment]
@camlloyd : https://anaconda.org/ome/bftools/files build 6.5.0-3 _appears_ to be ready for Windows. Let us know how it goes for you.

**Comment by camlloyd** [comment]
Looks good to me - thanks!

**Comment by joshmoore** [comment]
Great, thanks for letting us know. Just getting blosc installed in Azure on the other repositories then they should be available as well.

**Comment by joshmoore** [comment]
I think that's all three pages now. Let us know if you have any issues.
